# SOCRATA - LA METERS DATA
app_token = 'u5J73lOjqBNUeWShSs5EdlmJo'
username = 'juan.p.herrerasosa@gmail.com'
password = 'Juanpablacho2000.'


# API's endpoints
parking_meter_occupancy_api_endpoint = "e7h6-4a3e"
parking_meter_inventory_api_endpoint = "s49e-q6j2"

# Weather API
weather_key_api_endpoint = "37012b8dfefdabc9cd6f71e8d652545d"

# Bing Map API
bing_map_api_endpoint = 'AlNGMPsComhE6qmH93jIuZHIk9eKC15sOxpCMkr66NGDV0gx2ekOx0uDsODXfIvr'

# TicketMaster API key
tickemaster_api_endpoint = 'c1s7DnyWRzGxhroBT58nOo3YNzwG19o2'